name: Mirobot Apps
markdown: kramdown
collections:
  apps:
    output: true
    permalink: /:path/
exclude:
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
  - README.md
  - "*.zip"
  - bin
  - "*.psd"
